### ISSUE TITLE
Extension Fields are missing in json representation

### ISSUE THREAD

**Issue by mheuser** [HubSpot/jackson-datatype-protobuf#11]
Starting with commit ca2d79b9b6f67617dd3ab810ca8353bafbad228c fields that are added to a message via the extension mechanism are no more serialized to json. My guess is that the change from using message.getAllFields() to message.getDescriptorForType().getFields() in the serializer is the reason for that.

As workaround I just stick to an older release.

**Comment by jhaber** [comment]
Sorry for the heavily delayed response here, I'll try to fix this over the weekend

**Comment by jhaber** [comment]
Can you check out 046a1e53253893d56bc4573311a6b35919b7b72c I added support for reading and writing extension fields (you can now pass an `ExtensionRegistry` to the constructor of `ProtobufModule`). If it works for you I'll cut a release

**Comment by jhaber** [comment]
This was released as part of 0.9.4, let me know if it doesn't meet your needs and we can reopen the issue
