### ISSUE TITLE
protocol buffer maps are serialized as key-value lists

### ISSUE THREAD

**Issue by markusjevringgoeuro** [HubSpot/jackson-datatype-protobuf#13]
I would expect:

```
"my-key": "my-value"
```

What I get is:

```
"key": "my-key",
"value": "my-value"
```

**Comment by jhaber** [comment]
Sorry for the long delay. I just released a new version with Protobuf 3 support. More detail can be found [here](https://github.com/HubSpot/jackson-datatype-protobuf/blob/jackson29-proto3/README.md#protobuf-3-support). This includes special handling for maps, which should fix this issue.
