### ISSUE TITLE
protobuf 3.x support?

### ISSUE THREAD

**Issue by Nosfert** [HubSpot/jackson-datatype-protobuf#22]
Hi. 
I saw an earlier issue discussing boolean etc issues regarding protobuf 3.x

I wonder if this repo will have support for protobuf 3.x  ? 

Or do you know some way to register protobuf 3.x as a mapper to jackson ?

**Comment by Nosfert** [comment]
I think i solved it in a easier way.
Im leaving comment here with my solution so if someone in the future wants to they can hopefully do the same.

`
public class Proto3Serializer extends StdSerializer<EntityOrBuilder> {

    protected Proto3Serializer() {
        this(null);
    }

    protected Proto3Serializer(Class<EntityOrBuilder> t) {
        super(t);
    }

    @Override
    public void serialize(EntityOrBuilder value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        gen.writeRaw(JsonFormat.printer().omittingInsignificantWhitespace().includingDefaultValueFields().print(value));
    }
}

`

**Comment by jhaber** [comment]
Hi, whether we should use the native JSON format for protobuf3+ has come up before. You can find the conversation [here](https://github.com/HubSpot/jackson-datatype-protobuf/issues/12#issuecomment-240449294). If it works for your use-case, go for it. But as noted in the discussion, we'd be giving up a lot of features and flexibility by switching to that. So the plan is for this library to continue using its own serializer and deserializer, which will need to be updated to support protobuf3

**Comment by jhaber** [comment]
Sorry for the delay, I just released a new version of the library including support for Protobuf 3. See [here](https://github.com/HubSpot/jackson-datatype-protobuf/blob/jackson29-proto3/README.md#protobuf-3-support) for more details
