### ISSUE TITLE
Does the library support deserialization from byte[]?

### ISSUE THREAD

**Issue by thespags** [HubSpot/jackson-datatype-protobuf#64]
If I had a proto message and I wanted to deserialize it into a different representation with custom deserializes. Am I able to directly go from proto's byte[] representation instead of proto -> json -> my pojo.
```
SomeProto someProto;
AbstractMessage message = Any.pack(someProto)
  .unpack(SomoeProto.class);
reader.forType(SomeOtherPojo.class)
  .readValue(message.toByteArray());
```
Thanks.

**Comment by jhaber** [comment]
Hi, thanks for the question. This library is specifically concerned with reading/writing protobufs as JSON. If you're interesting in using Jackson to read/write the protobuf wire format directly, I think you're looking for [jackson-dataformat-protobuf](https://github.com/FasterXML/jackson-dataformats-binary/tree/master/protobuf) (the naming similarity is confusing, but the important distinction is datatype vs. dataformat)

**Comment by thespags** [comment]
Thanks for the clarification. Unfortunately jackson-dataformat-protobuf doesn't fully support protoo v3.
