### ISSUE TITLE
Make ProtobufModule friendly to ObjectMapper.findAndRegisterModules()

### ISSUE THREAD

**Issue by linux-china** [HubSpot/jackson-datatype-protobuf#66]
According to https://fasterxml.github.io/jackson-databind/javadoc/2.10/com/fasterxml/jackson/databind/ObjectMapper.html#findModules--

and ObjectMapper's module could be loaded by service loader automatically like following code: 

```
objectMapper.findAndRegisterModules()
```

and it's not hard, just create resources/META-INF/services/com.fasterxml.jackson.databind.Module file and filled with ProtobufModule full class name

```
com.hubspot.jackson.datatype.protobuf.ProtobufModule
```

Any plan to upgrade to Jackson 2.10?  Thanks.

**Comment by jhaber** [comment]
I'm slightly concerned that doing this could cause issues for existing users. However, it seems like the intent is for all Jackson modules to register themselves this way so we should probably do it

**Comment by jhaber** [comment]
Are you running from source or would you like me to cut a release with these changes?
