### ISSUE TITLE
Requesting Jackson 2.10 Support

### ISSUE THREAD

**Issue by Andy-L** [HubSpot/jackson-datatype-protobuf#69]
Jackson 2.10 has been [released](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10) and has made some changes that are incompatible with the 2.9-supporting release of jackson-datatype-protobuf.

Is there an ETA on jackson-datatype-protobuf support for jackson 2.10.x?

**Comment by jhaber** [comment]
Do you have more details on what problems you're seeing? The default branch in this repo is now using Jackson 2.10 and all of our tests are passing:
https://travis-ci.org/github/HubSpot/jackson-datatype-protobuf/builds/675096993

I can cut a release with that, but I don't think we made any code changes as part of the upgrade to Jackson 2.10

**Comment by navaneeth-spotnana** [comment]
Which version should I use from maven?

**Comment by cowtowncoder** [comment]
Since `2.11.0` has been released as well, would perhaps be good to test compatibility, add to README (version up to `2.9` are mentioned).

One thing I can probably do is add dependency to this module from

github.com:cowtowncoder/jackson-compat-minor

project, to help maintain compatibility.

**Comment by jhaber** [comment]
Our test suite seems to pass against 2.11.0 as well, I made that the default branch and am cutting a release

**Comment by jhaber** [comment]
Since the same code now seems to work on Jackson 2.9, 2.10, and 2.11, I'll move to a single branch setup. We can use travis to test against multiple Jackson versions:
https://github.com/HubSpot/jackson-datatype-protobuf/blob/6ee5151de67f405f74a03deb03a67ee4b028f0f3/.travis.yml#L11-L14

**Comment by cowtowncoder** [comment]
Neat, pretty cool that can be made to work so easily.

I also tested this module at work, for real use case. Lots of (mostly) legacy protobuf services (there will be newer ones using gRPC, but these are "raw" ones), and many either manually transform from proto to pojos, or use `protobuf-java-format`. Tried "vanilla Jackson" too and quickly found all the issues this module nicely works around (plenty of metadata to ignore, but beyond ~7 getters, also the whole "get string / get as bytes" and similar alternatives to suppress). Of 3 approaches, `jackson-datatype-protobuf` produced the best serialization by far.

**Comment by jhaber** [comment]
Really glad to hear it's working well for you 😄 

I've updated the readme to reflect the new versioning strategy:
https://github.com/HubSpot/jackson-datatype-protobuf/blob/master/README.md#versions

Also 0.9.12 has been released and should show up in Maven Central soon (with support for Jackson 2.10 and 2.11). 

@Andy-L can you try out 0.9.12 and confirm that it works for you?

**Comment by cowtowncoder** [comment]
@jhaber Excellent! I will probably do some advocating at work too. And who knows, maybe we'll find improvement suggestions to log or something :)
