### ISSUE TITLE
protobuf 2.6.1

### ISSUE THREAD

**Issue by hgschmie** [HubSpot/jackson-datatype-protobuf#7]
Using the protobuf 2.6.1 library in this datatype is actually a problem. Any class that has been built using protobuf 2.5.0 will no longer work if an extension registry is used:

e.g. the Apache Mesos protos file contains 

```java
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
```

at the very top. If this file happens to actually use an extension, it will contain code similar to this:

```java
public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.apache.mesos.Protos.DockerContainerizerInformation.info);
  }
```

Now, the `registry.add()` method call will call `ExtensionRegistry#add(GeneratedMessage.GeneratedExtension<?, ?>)`. This is the auto-generated code for google protobuf 2.5.0

In 2.6.1, this API call no longer exists.

So any code calling this method will fail with spectacular NoClassDefErrors at startup if any extension is registered.

Can we move back to 2.5.0 which seems to be the most common version of the protobuf code out in the wild?

**Comment by HiJon89** [comment]
I'm not sure I understand, if you exclude 2.6.1 and bring in 2.5.0 in your project it doesn't work?

**Comment by HiJon89** [comment]
Downgraded to 2.5.0 as part of 5ab842f93fe890ab10417ff023bf7241d88c130e
