### ISSUE TITLE
IllegalArgumentException: Unable to get default instance for type class com.google.protobuf.MapEntry

### ISSUE THREAD

**Issue by pbsf** [HubSpot/jackson-datatype-protobuf#75]
I'm receiving an `IllegalArgumentException` when attempting to **deserialize** a **proto3** that contains `map` fields.
```
IllegalArgumentException: Unable to get default instance for type class com.google.protobuf.MapEntry
```

Jackson version: 2.10.1.
jackson-datatype-protobuf version: 0.9.12.

Enums, repeated fields and oneOfs all work fine though. Serialization of map fields work fine as well.

This project contains unit tests for maps, so it bugs me that I couldn't get it to work. I copied the `writeAndReadBack` utilitary method for unit tests and was able to reproduce it easily.

```
// .proto file.
message SomeMsg {
    map<string, string> map_entry = 1;
}

```

```
// .kt file.
val msg = SomeMsg.newBuilder()
    .putMapEntry("1","2")
    .build()

val mapper = ObjectMapper().registerModule(ProtobufModule())
writeAndReadBack(mapper, msg) // Throws exception.
```

**Comment by jhaber** [comment]
What version of protobuf-java are you using?

**Comment by pbsf** [comment]
protobuf-java version: 3.9.0.

That seems to be the problem indeed. What is the recommended verison to use with this project? I can work on a patch to address the limitation on the 3.9.0 if you could help me with some pointers.

**Comment by pbsf** [comment]
I was using jackson-datatype-protobuf version: **0.9.2** rather than **0.9.12**. Using 0.9.12 fixes this issue. My bad.
