### ISSUE TITLE
dose it support for LocalDateTime?

### ISSUE THREAD

**Issue by wangxi761** [HubSpot/jackson-datatype-protobuf#83]
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.google.protobuf.Timestamp` from String "2021-03-16T01:50:38": Failed to parse timestamp: missing valid timezone offset.

**Comment by jhaber** [comment]
Hi there, we currently delegate to protobuf library itself for parsing timestamps:
https://github.com/HubSpot/jackson-datatype-protobuf/blob/5d403ef47a07a13433cfdca08fb6e6fe1ec7a96b/src/main/java/com/hubspot/jackson/datatype/protobuf/builtin/deserializers/TimestampDeserializer.java#L24

I'm not sure that we want to be in the business of trying to parse any more date formats than that
