### ISSUE TITLE
Empty fields should be included in serialization in some use cases

### ISSUE THREAD

**Issue by jkebinger** [HubSpot/jackson-datatype-protobuf#9]
Used in conjunction with rosetta, the behavior to omit empty proto fields causes query execution to fail, because the empty fields do not get bound in the query.

```java
dao.upsertAll(Lists.newArrayList(ED_P53_1.toBuilder().clearCategory().build()));
``` 
fails with 
```
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: Unable to execute, no named parameter matches "category" and no positional param for place 10 (which is 11 in the JDBC 'start at 1' scheme) has been set. [statement:"INSERT IGNORE INTO eventDetails(id, domain, portalId, emailCampaignId, email, emailAccountId, eventType, status, reason, date, category) VALUES (:id, :domain, :portalId, :emailCampaignId, :email, :emailAccountId, :eventType, :status, :reason, :date, :category)", located:"null", rewritten:"null", arguments:{ positional:{}, named:{date:10,reason:'Address doesn't exist',emailAccountId:123,domain:'Domain',portalId:53,emailCampaignId:123456,eventType:'SENDGRID_BOUNCE',id:'p53cat1',email:'test@email.com',status:'5.1.1'}, finder:[]}]
```

**Comment by jhaber** [comment]
I can make the serializer respect JSON inclusion setting of ALWAYS since that will be purely additive. Unfortunately for backwards compatibility I wouldn't want to respect the other settings since that would remove fields that are currently serialized

**Comment by jhaber** [comment]
The other question is whether we write the default field value or `null` for non-populated fields

**Comment by jhaber** [comment]
I'm thinking we want `null`, otherwise a test like this would fail:

```java
Proto a = Proto.getDefaultInstance();
Proto b = mapper.readValue(mapper.writeValueAsString(a), Proto.class);

assertThat(b).isEqualTo(a);
```

because when `a` would have no fields populated, but `b` would have all fields populated with default values, so you're losing information
